all: run1

run1:
	javac BaquedanoThread.java MiRunnable.java Funciones.java
	java BaquedanoThread Funciones

run2:
	javac BaquedanoForks.java Funciones.java
	java BaquedanoForks Funciones

clean:
	rm -f *.class